name: Add redirects-needed label
on:
  workflow_run:
    workflows: ['Redirects Workflow']
    types:
      - completed
jobs:
  addRedirectsNeededLabel:
    name: Add redirects-needed label
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: 'Download artifact'
        uses: actions/github-script@v6.4.0
        with:
          script: |
            const { getArtifact } = require('./.github/workflows/scripts/check_for_redirects');
            const fs = require('fs');
            getArtifact({github, context, fs});
