name: Add redirects-needed label
on:
  workflow_run:
    workflows: ['Redirects Workflow']
    types: [completed]
env:
  ARTIFACT_NAME: redirectsArtifact
jobs:
  addRedirectsNeededLabel:
    name: Add redirects-needed label
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/github-script@v6.4.0
        env:
          WORKSPACE: ${{ github.workspace }}
        with:
          script: |
            const { getArtifact } = require('./.github/workflows/scripts/check_for_redirects');
            const fs = require('fs');
            const artifactName = process.env.ARTIFACT_NAME;
            const workspace = process.env.WORKSPACE
            getArtifact({github, context, fs, artifactName, workspace});
      - name: Unzip artifact
        run: unzip '${{ env.ARTIFACT_NAME }}.zip'
      - name: Add label to PR
        uses: actions/github-script@v6.4.0
        env:
          WORKSPACE: ${{ github.workspace }}
        with:
          script: |
            const { addRedirectsNeededLabel } = require('./.github/workflows/scripts/check_for_redirects');
            const fs = require('fs');
            const artifactName = process.env.ARTIFACT_NAME;
            const workspace = process.env.WORKSPACE
            console.log('workspace ', workspace);
            addRedirectsNeededLabel({github, context, fs, artifactName, workspace});
