name: Redirects Workflow
on:
  pull_request:
    types: [opened, synchronize]
env:
  DIFF_DIRECTORIES: 'src/pages src/fragments'
jobs:
  checkIfRedirectsAreNeeded:
    name: Check if redirects are needed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get count of deleted files
        uses: actions/github-script@v6.4.0
        id: set-deleted-files-count
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const { getDeletedFiles } = require('./.github/workflows/scripts/check_for_redirects.js');
            return getDeletedFiles({github, context, core});
      - name: Create artifact containing deleted file count
        id: create-artifact-name
        run: |
          artifact_name="pr${{ github.event.pull_request.number }}"
          echo "ARTIFACT_NAME=${artifact_name}" >> "$GITHUB_OUTPUT"
          echo ${{ steps.set-deleted-files-count.outputs.result }} > "${artifact_name}.txt"
      - name: Upload count of deleted files artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.create-artifact-name.outputs.ARTIFACT_NAME }}
          path: '${{ steps.create-artifact-name.outputs.ARTIFACT_NAME }}.txt'
