name: Redirects Workflow
on:
  pull_request:
    types: [opened, synchronize]
env:
  DIFF_DIRECTORIES: 'src/pages src/fragments'
  ARTIFACT_NAME: 'redirectsArtifact'
jobs:
  checkIfRedirectsAreNeeded:
    name: Check if redirects are needed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get count of deleted files
        uses: actions/github-script@v6.4.0
        id: set-deleted-files-count
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const { getDeletedFiles } = require('./.github/workflows/scripts/check_for_redirects.js');
            return getDeletedFiles({github, context});
      - name: Create artifact containing deleted file count
        id: create-artifact-name
        env:
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo ${{ env.GITHUB_PR_NUMBER }} >> "${{ env.ARTIFACT_NAME }}.txt"
          echo ${{ steps.set-deleted-files-count.outputs.result }} >> "${{ env.ARTIFACT_NAME }}.txt"
      - name: Upload count of deleted files artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: '${{ env.ARTIFACT_NAME }}.txt'
