name: Redirects Workflow
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
env:
  DIFF_DIRECTORIES: 'src/pages src/fragments'
jobs:
  checkIfRedirectsAreNeeded:
    name: Check if redirects are needed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get count of deleted files
        uses: actions/github-script@v6.4.0
        id: set-deleted-files-count
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const { getDeletedFiles } = require('./.github/workflows/scripts/check_for_redirects.js');
            return getDeletedFiles({github, context, core});
