name: Requested Reviewers
on:
  pull_request:
    types: [review_requested]
jobs:
  requestedReviewers:
    name: Requested reviewers
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Used to add comment to PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get list of requested reviewers
        uses: actions/github-script@v6.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { requestedReviewers } = require('./.github/workflows/scripts/requested_reviews.js');
            requestedReviewers({github, context});
