name: Verify Approvers
on:
  pull_request_review:
    types: [submitted]
jobs:
  verifyApproval:
    name: Verify approvals
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Used to add comment to PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check if approver is from requested reviewers
        uses: actions/github-script@v6.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { verifyApprovers } = require('./.github/workflows/scripts/verify_approvers.js');
            verifyApprovers({github, context});
